
import { Language } from './types';

export const UI_STRINGS = {
  [Language.ENGLISH]: {
    login: "Login",
    register: "Register",
    username: "Username",
    password: "Password",
    study: "Study",
    review: "Review",
    test: "Test",
    dictionary: "Dictionary",
    myDictionary: "My Dictionary",
    allDictionary: "All Words",
    logout: "Logout",
    kidsMode: "Kids Mode",
    adultsMode: "Adults Mode",
    changeLang: "Language",
    learned: "Learned",
    seen: "Seen",
    testLocked: "Learn 40 words to unlock Test mode!",
    back: "Back",
    finish: "Finish",
    correct: "Correct!",
    wrong: "Wrong, try again!",
    next: "Next",
    congrats: "Congratulations!",
    startStudying: "Let's Start!",
    emptyDictionary: "No words learned yet.",
    levelStart: "Start",
    levelMedium: "Medium",
    levelAdvanced: "Advanced",
    selectLevel: "Select your level",
    authError: "Login and password must be at least 6 characters long.",
    registrationSuccess: "Registration successful! Logging in...",
    invalidCredentials: "Invalid username/email or password. Please check your credentials.",
    loginHint: "Use the same username/email you registered with."
  },
  [Language.RUSSIAN]: {
    login: "Войти",
    register: "Регистрация",
    username: "Логин",
    password: "Пароль",
    study: "Учеба",
    review: "Повторение",
    test: "Тест",
    dictionary: "Словарь",
    myDictionary: "Мой словарь",
    allDictionary: "Все слова",
    logout: "Выйти",
    kidsMode: "Детский режим",
    adultsMode: "Взрослый режим",
    changeLang: "Язык",
    learned: "Выучено",
    seen: "Просмотрено",
    testLocked: "Выучите 40 слов, чтобы открыть тест!",
    back: "Назад",
    finish: "Завершить",
    correct: "Верно!",
    wrong: "Неверно, попробуй еще раз!",
    next: "Далее",
    congrats: "Поздравляем!",
    startStudying: "Начать учиться!",
    emptyDictionary: "Словарь пока пуст.",
    levelStart: "Начальный",
    levelMedium: "Средний",
    levelAdvanced: "Продвинутый",
    selectLevel: "Выберите ваш уровень",
    authError: "Логин и пароль должны быть не менее 6 символов.",
    registrationSuccess: "Регистрация успешна! Вход в систему...",
    invalidCredentials: "Неверный логин/email или пароль. Проверьте данные.",
    loginHint: "Используйте тот же логин/email, с которым регистрировались."
  },
  [Language.ARMENIAN]: {
    login: "Մուտք",
    register: "Գրանցում",
    username: "Օգտանուն",
    password: "Գաղտնաբառ",
    study: "Ուսում",
    review: "Կրկնություն",
    test: "Թեստ",
    dictionary: "Բառարան",
    myDictionary: "Իմ բառարանը",
    allDictionary: "Բոլոր բառերը",
    logout: "Դուրս գալ",
    kidsMode: "Մանկական ռեժիմ",
    adultsMode: "Մեծահասակների ռեժիմ",
    changeLang: "Լեզու",
    learned: "Սովորած",
    seen: "Տեսած",
    testLocked: "Սովորեք 40 բառ թեստը բացելու համար:",
    back: "Հետ",
    finish: "Ավարտել",
    correct: "Ճիշտ է:",
    wrong: "Սխալ է, նորից փորձիր:",
    next: "Հաջորդը",
    congrats: "Շնորհավորում ենք:",
    startStudying: "Սկսել սովորել",
    emptyDictionary: "Բառարանը դեռ դատարկ է:",
    levelStart: "Սկսնակ",
    levelMedium: "Միջին",
    levelAdvanced: "Բարձր",
    selectLevel: "Ընտրեք ձեր մակարդակը",
    authError: "Մուտքանունը և գաղտնաբառը պետք է լինեն առնվազն 6 նիշ:",
    registrationSuccess: "Գրանցումը հաջողվեց: Մուտք գործում...",
    invalidCredentials: "Սխալ մուտքանուն/էլ. փոստ կամ գաղտնաբառ: Ստուգեք տվյալները:",
    loginHint: "Օգտագործեք նույն մուտքանունը/էլ. փոստը, որով գրանցվել եք:"
  }
};
